# Generated by Django 3.2.9 on 2021-12-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_auto_20211213_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='avg_rate',
            new_name='average',
        ),
    ]
